### ISSUE TITLE
Cannot delete project without columns

### ISSUE THREAD

**Issue by ernestorefinepro** [opencultureconsulting/openrefine-client#18]
### How to reproduce

- Create a project from the clipboard with one column and one value `EN`.
- Set the name to `main_project`
- Once the project is created go to the column and remove it. This left the project without any columns
- Execute `./openrefine-client --delete 'main_project'` and you will see the following error:
```
./openrefine-client --delete 'main_project'
Traceback (most recent call last):
  File "/home/felix/openrefine-client/refine.py", line 35, in <module>
  File "/home/felix/openrefine-client/google/refine/__main__.py", line 256, in main
  File "/home/felix/openrefine-client/google/refine/cli.py", line 140, in delete
  File "/home/felix/openrefine-client/google/refine/refine.py", line 371, in __init__
  File "/home/felix/openrefine-client/google/refine/refine.py", line 417, in get_models
KeyError: 'keyColumnName'
[1976071] Failed to execute script refine
```

### Environment details

- OpenRefine 3.4.1
- OS: Ubuntu 20-04
- Java: 1.8

**Comment by felixlohmeier** [comment]
Hi @ernestorefinepro ,

The cause of this problem is probably the [initialization of the project via the RefineProject() class in the delete() function](https://github.com/opencultureconsulting/openrefine-client/blob/0df6050deb9dc923ae75a542758dd6ac2184d7bb/google/refine/cli.py#L140) which triggers [get_models()](https://github.com/opencultureconsulting/openrefine-client/blob/0df6050deb9dc923ae75a542758dd6ac2184d7bb/google/refine/refine.py#L403). That would be this line in the log:
```
File "/home/felix/openrefine-client/google/refine/refine.py", line 417, in get_models
```

You could test if the error does not occur with plain curl. Example for project id 1761702727570:
```
curl --data project="1761702727570" "http://localhost:3333/command/core/delete-project?csrf_token=$(curl -s http://localhost:3333/command/core/get-csrf-token | cut -d '"' -f 4)"
```

Is this error an important problem for your use case or did you just want to let me know?

**Comment by ernestorefinepro** [comment]
With the curl command, the project can be deleted without issues. 
For my case, the delete command error is an issue because I am automating the processing of several files with OpenRefine. The error creates some noise in the process.
