### ISSUE TITLE
templating with options --mode=record-based and --splitToFiles=true fails with exception "missing or bad template"

### ISSUE THREAD

**Issue by felixlohmeier** [opencultureconsulting/openrefine-client#6]
templating export with options `--splitToFiles=true` and `--mode=record-based` fails with the following exception:
<pre>
22:54:17.182 [          org.mortbay.log] /command/core/export-rows/templating.txt: java.io.IOException: M
issing or bad template (8ms)
Traceback (most recent call last):
  File "refine.py", line 31, in <module>
  File "google/refine/__main__.py", line 269, in main
  File "google/refine/cli.py", line 319, in templating
  File "google/refine/refine.py", line 454, in export_templating
  File "google/refine/refine.py", line 370, in do_raw
  File "google/refine/refine.py", line 85, in urlopen
Exception: HTTP 500 "Missing or bad template" for http://127.0.0.1:8889/command/core/export-rows/templati
ng.txt
        {'engine': '{"facets": [], "mode": "record-based"}', 'suffix': '', 'format': 'template', 'encodin
g': 'UTF-8', 'project': '1822473731467', 'prefix': '', 'separator': '', 'template': '{{forNonBlank(with(r
ow.columnNames[0],cn,cells[cn].value),v,"===|||THISISTHEBEGINNINGOFANEWRECORD|||===")}}{{
</pre>

last working version: v0.3.4

**Comment by felixlohmeier** [comment]
I will keep this issue open until v0.3.9 is published

**Comment by felixlohmeier** [comment]
https://github.com/opencultureconsulting/openrefine-client/releases/tag/v0.3.9
