### ISSUE TITLE
socket.error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by dietleintech** [opencultureconsulting/openrefine-client#9]
Hey, when i try to create a project (`./openrefine-client_0-3-8_linux --create test.txt--skipDataLines=65 --limit=1`), i am getting following error:
```
Traceback (most recent call last):
  File "refine.py", line 31, in <module>
  File "google/refine/__main__.py", line 251, in main
  File "google/refine/cli.py", line 127, in create
  File "google/refine/refine.py", line 272, in new_project
  File "google/refine/refine.py", line 83, in urlopen
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 429, in open
  File "urllib2.py", line 447, in _open
  File "urllib2.py", line 407, in _call_chain
  File "urllib2_file.py", line 207, in http_open
  File "urllib2_file.py", line 281, in do_open
  File "urllib2_file.py", line 130, in send_data
  File "httplib.py", line 873, in send
  File "socket.py", line 228, in meth
socket.error: [Errno 32] Broken pipe
[30713] Failed to execute script refine
```
Serverside log: `refine] POST /command/core/create-project-from-upload (33749ms)`

Export and List functions are working without problems.
As server i'm using the current linux-kit.

I dont have any clue, why it crashes.

**Comment by felixlohmeier** [comment]
Hey @dietleintech,

> As server i'm using the current linux-kit

You mean OpenRefine 3.3? Unfortunately the client does not yet support the current version (#7). It should work up to OpenRefine 3.2.

**Comment by dietleintech** [comment]
Ok, solved... works with 3.2 - thanks for the fast answer!
